### PR TITLE
Enable Navigation in ROS 2 Foxy and Fix Configuration Issue in pointcloud_to_laserscan

### PR DESCRIPTION
**Pull request by luispri2001**
### Summary
This pull request proposes a dedicated branch for ROS 2 Foxy, adding support for navigation and fixing a configuration in `pointcloud_to_laserscan`.

### Context
Creating a `foxy` branch addresses Foxy’s unique compatibility needs, allowing users to work with optimized configurations without affecting other ROS versions. This is especially useful for the Unitree Go2 robot, which comes with ROS 2 Foxy pre-installed, enabling users to run these settings on the robot without modifying the existing ROS setup.

### Changes
- **Navigation Support in ROS 2 Foxy**: Adjusted `nov2` configuration parameters.
- **Configuration Fix for `pointcloud_to_laserscan`**: Minor update to `go2_driver` launch file for proper laser scan conversion.
- **New `foxy` Branch**: Contains Foxy-specific changes for targeted development.

### CODE REVIEW

**Comment by SurajBorate** [comment]
`I have a mid360 lidar what changes do I have to do?

**Comment by Juancams** [comment]
Hi!

We still have to add the option to use the mid360 lidar to the launcher, but if you launch it from within the robot and grab the pointcloud topic, it should work.

Regards!!

**Comment by Bailey-24** [comment]
hello, now I can't see the mid360 in the option, do you have a try?

**Comment by Juancams** [comment]
It will be added in the next few days

**Comment by Bailey-24** [comment]
Thanks in advance

**Comment by HowieYang0** [comment]
Can it work with ROS2 Humble? If not, what needs to be done?

**Comment by Juancams** [comment]
Yes, it works with ROS 2 Humble ^^

**Pull request merged**
